config/routes.rb
Rails.application.routes.draw do

  resources :users do
	  resources :posts
	  resources :comments
	  resources :userfriends
	end
  get '/' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post
	belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
	has_many :posts
	has_many :comments
	has_many :users, through: :user_friends
	has_many :user_friends
end

app/models/user_friend.rb
class UserFriend < ApplicationRecord
	belongs_to :user
	belongs_to :user , foreign_key: "friend_id", class_name: "User"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def current_user 
  	if session[:user_id]
  		User.find(session[:user_id])
  		# sets session with current user.
  	end
  	# @post = Post.all(params[:post][:content])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @user = current_user
    # setting user as current user
    @comment = Comment.new
    # making new comment
    @post_id = params[:post_id]
    # setting the post id
  end

  def create
    puts "#{params[:post_id]}"
    @comment = Comment.create(content: params[:comment][:content], post_id: params[:post_id], user_id: current_user.id)
    # creating the comment with post.id it's tied to and user it's tied too.
    redirect_to user_posts_path
  end

  def new
  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :user_id, :post_id)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = current_user
    @post = Post.new
    @posts = @user.posts
  end

  def create
    Post.create(content: params[:post][:content], user_id: current_user.id)
    puts "#{params.inspect}"
    redirect_to user_posts_path
    # creates new post on the post.id with user.id
  end

  def new
  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
  end

  private
  def post_params
    params.require(:post).permit(:content, :user_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
  end

  def create
      puts "Params Are: #{params.inspect}"
    @user = User.where(username: params[:username], password: params[:password]).first
    # puts "DID WE GET THE USER? #{@user}"
    if @user
      session[:user_id] = @user.id
      redirect_to user_path @user
    else
      redirect_to login_path
    end
    # creates session on log in
  end

  def new
    @user = current_user
  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
    session[:user_id] = nil
    # logs user out
    redirect_to login_path
  end

  
end

app/controllers/userfriends_controller.rb
class UserfriendsController < ApplicationController
  def index
    @users = User.all
    @user = current_user
  end

  def create
  end

  def new
    @friend = UserFriend.create(friend_id: params[:user_id], user_id: current_user.id)
    redirect_to user_path current_user 
  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
    UserFriend.find(params[:id]).destroy
    redirect_to user_path current_user
  end

  private
  def userfriends_params
    params.require(:user).permit(:user_id, :friend_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.new
    # create new user
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Your account was created successfully."
      redirect_to user_path @user
    else
      flash[:alert] = "There was a problem saving your account."
      redirect_to new_user_path
    end
    # save new user, unless there is a problem
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
    # finds the user to with that id
    puts "New params: #{params.inspect}"
  end

  def show
     @user = User.find(params[:id])
     # goes to current user home page
     @current = current_user
     # just here till original home button works
  end

  def update
    @user = User.find(params[:id]).update_attributes(params[:user])
    # finds current user and updates attr
    puts "These are the params #{params.inspect}"
    redirect_to user_path 
  end

  def destroy
    puts ": #{params.inspect}"
    current_user.destroy
    # deletes current user
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:fname, :lname, :username, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/userfriends_helper.rb
module UserfriendsHelper
end

app/helpers/users_helper.rb
module UsersHelper
	# def test
	# 	"Hello, World!"		
	# end

	# def headline(headline)
	# 	content_tag :h1, headline
	# end

end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<%= form_for [@user, @comment] do |f| %>
	<%= hidden_field_tag "post_id", @post_id %>
	<%= f.label :content, "New Comment"%>
	<%= f.text_area :content %>
	<%= f.submit %>
<% end %>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div id="head">
  	<%if @user %>
		<%= link_to('Home Page', "#{request.base_url}/users/#{@user.id}", :class => "btn", :id => "home") %>
		<%= link_to('Edit', "#{request.base_url}/users/#{@user.id}/edit", :class => "btn") %>
		<%= link_to('Post', "#{request.base_url}/users/#{@user.id}/posts", :class => "btn") %>
		<%= link_to('All Users', "#{request.base_url}/users/#{@user.id}/userfriends", :class => "btn") %>
		<%= link_to('Logout', "#{request.base_url}/logout", :class => "btn") %>
	<% else %>
		<%= link_to('Login', "#{request.base_url}/login", :class => "btn") %>
		<%= link_to('Create Account', "#{request.base_url}/users", :class => "btn") %>
	<% end %>
	</div>
    <%= yield %>
  </body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>
<hr>
<%= form_for [@user, @post] do |f| %>
	<%= f.label :content, "New Post"%>
	<%= f.text_area :content %>
	<%= f.submit %>
<% end %>
<br>

<% @posts.each do |post| %>
	Post: <%= post.content %>
	<%= time_ago_in_words(post.created_at) %> ago
<br>
	Comments: <% post.comments.each do |comment| %>
	<br>
		<%= comment.content %>
		<%= time_ago_in_words(comment.created_at) %> ago
	<% end %>
	<br>
	<%= link_to('Comment', "#{request.base_url}/users/#{@user.id}/comments?post_id=#{post.id}", :class => "btn") %>
<hr>
<% end %>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/userfriends/create.html.erb
<h1>Userfriends#create</h1>
<p>Find me in app/views/userfriends/create.html.erb</p>

app/views/userfriends/destroy.html.erb
<h1>Userfriends#destroy</h1>
<p>Find me in app/views/userfriends/destroy.html.erb</p>

app/views/userfriends/edit.html.erb
<h1>Userfriends#edit</h1>
<p>Find me in app/views/userfriends/edit.html.erb</p>

app/views/userfriends/index.html.erb
<h1>Userfriends#index</h1>
<p>Find me in app/views/userfriends/index.html.erb</p>

<br>
<% @users.each do |user| %>
	Username: <%= user.username %>
	<%= link_to('Follow', new_user_userfriend_path(user)) %>
	<br>
<% end %>

app/views/userfriends/new.html.erb
<h1>Userfriends#new</h1>
<p>Find me in app/views/userfriends/new.html.erb</p>

app/views/userfriends/show.html.erb
<h1>Userfriends#show</h1>
<p>Find me in app/views/userfriends/show.html.erb</p>

app/views/userfriends/update.html.erb
<h1>Userfriends#update</h1>
<p>Find me in app/views/userfriends/update.html.erb</p>

app/views/users/_user.html.erb
<%= user.fname %>

app/views/users/_user_form.html.erb
<%= form_for @user, html: {method: :put} do |f| %>
	<%= f.label :fname, "First Name"%>
	<%= f.text_field :fname %>
	<%= f.label :lname, "Last Name"%>
	<%= f.text_field :lname %>
	<%= f.label :username, "Username"%>
	<%= f.text_field :username %>
	<%= f.label :password, "Password"%>
	<%= f.password_field :password %>
	<%= f.submit %>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>
<hr>
<%= form_for @user, html: {method: :put} do |f| %>
	<%= f.label :fname, "First Name"%>
	<%= f.text_field :fname %>
	<%= f.label :lname, "Last Name"%>
	<%= f.text_field :lname %>
	<%= f.label :username, "Username"%>
	<%= f.text_field :username %>
	<%= f.label :password, "Password"%>
	<%= f.password_field :password %>
	<%= f.submit %>
<% end %>
<hr>
<%= link_to('Delete', "#{request.base_url}/users/#{@user.id}", :method => :delete, :class => "btn") %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

<%= form_for @user do |f| %>
	<%= f.label :fname, "First Name"%>
	<%= f.text_field :fname %>
	<%= f.label :lname, "Last Name"%>
	<%= f.text_field :lname %>
	<%= f.label :username, "Username"%>
	<%= f.text_field :username %>
	<%= f.label :password, "Password"%>
	<%= f.password_field :password %>
	<%= f.submit %>
<% end %>

<%= flash[:alert] if flash[:alert] %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>


<%= render 'user_form' %>

app/views/users/show.html.erb
<hr>
<%= link_to('User Home Page', "#{request.base_url}/users/#{@current.id}", :class => "btn") %>
<hr>
<h1><%= @user.fname + " " + @user.lname %></h1>
<p><%= render 'user', user: @user %></p>

<hr>
<h1>Friends</h1>
<% @user.user_friends.each do |friend| %>
 <h1><%= User.find(friend.friend_id).username %></h1>
 <%= link_to('Visit Page', "#{request.base_url}/users/#{friend.friend_id}", :class => "btn") %>
 <%= link_to('Unfollow', user_userfriend_path(@user, friend), method: :delete, :class => "btn") %>
<% end %>
<hr>
<h1><%= @user.username %></h1>

<% @user.posts.each do |post| %>
	<h1 class="post"><%= post.content %></h1>
	<%= link_to('Comment', "#{request.base_url}/users/#{@user.id}/comments?post_id=#{post.id}", :class => "btn") %>
		<% post.comments.each do |comment| %>
		 <p class="comment"><%= comment.content %></p>
		<% end %>
	<hr>
<% end %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>